wrap: true
margins:
  left: 5
  right: 5


# auto play the presentation with the following delay in seconds
# autoAdvanceDelay: 2

# slide auto-splitting level
slideLevel: 2

# make lists appear one at a time by default
# incrementalList: true


# use iterm2 escape sequences for images
images:
  backend: iterm2

# COLORS CONFIGURATION
# the properties that can be given a list of styles are:
#
# blockquote, borders, bulletlist, codeblock, code, definitionlist, definitionterm, emph, header, imagetarget, imagetext, linktarget, linktext, math, orderedlist, quoted, strikeout, strong, tableheader, tableseparator, underline
#
#
# The accepted styles are:
#
# bold, italic, dullBlack, dullBlue, dullCyan, dullGreen, dullMagenta, dullRed, dullWhite, dullYellow, onDullBlack, onDullBlue, onDullCyan, onDullGreen, onDullMagenta, onDullRed, onDullWhite, onDullYellow, onVividBlack, onVividBlue, onVividCyan, onVividGreen, onVividMagenta, onVividRed, onVividWhite, onVividYellow, underline, vividBlack, vividBlue, vividCyan, vividGreen, vividMagenta, vividRed, vividWhite, vividYellow
#
# Also accepted are styles of the form rgb#RrGgBb and onRgb#RrGgBb, where Rr Gg and Bb are hexadecimal bytes (e.g. rgb#f08000 for an orange foreground, and onRgb#101060 for a deep purple background).
theme:
  header: [rgb#2AB300, bold, underline]
  emph: [italic]
  strong: [dullWhite, bold]
  strikeout: [dullGreen]
  underline: [underline]
  bulletList: [rgb#3090FF, bold]
  orderedList: [rgb#3090FF]
  codeBlock: [onRgb#202020]
  blockQuote: [onRgb#202020]
  imageTarget: [onDullWhite, vividRed]
  borders: [rgb#108000]

eval:
  h1:
    command: toilet -f pagga
    fragment: false
    replace: true
  h2:
    command: toilet -f smblock
    fragment: false
    replace: true
  h3:
    command: toilet -f future
    fragment: false
    replace: true
  h4:
    command: tr [:lower:] [:upper:] | toilet -f smbraille
    fragment: false
    replace: true


