# autogenerated by txs
#include:etoolbox
#include:pgf
#include:pgfkeys
#include:pgfopts
#include:tikz
\bwpixelart{arg1}{arg2}#S
\tikzbwpixelart{arg1}{arg2}{arg3}#S
\\bwpixelart#S
\\tikzbwpixelart#S
\pgfparserdef#S
\pgfparserparse#S
\pgfparserswitch#S
